# Tranquilpeak
# Version : 0.5.3-BETA
# Author : Thibaud Leprêtre

baseURL = "https://wegeinie.github.io/"
languageCode = "pl"
defaultContentLanguage = "pl"
title = "Wege i nie"
theme = "hugo-tranquilpeak-theme"
disqusShortname = "wege-i-nie"
googleAnalytics = "UA-258384231-1"
paginate = 7
canonifyurls = true

[permalinks]
  posts = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

# ------
# Markup
# ------
[markup]
  # Set startLevel = 1 to support # title (<h1>title</h1>) otherwise table of content is blank/empty
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

# ------
# Author
# ------
[author]
  name = "Wege i nie"
  bio = "**Kuchnia rodzinna, nie tylko roślinna.**"
  bio2 = "Blog zaczęłam prowadzić w lutym 2023 roku. Ja - weganka, mąż wszystkożerny, a półtoraroczna córka najchętniej je jajka, parówki, kiwi, truskawki, awokado, kapary, rosół i masło. Zobaczymy, co będzie dalej."
  picture = "/img/wege-i-nie-logo-512.png"

# ------------
# Sidebar menu
# ------------
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-utensils\" aria-hidden=\"true\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "categories"
  name = "Categories"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-bookmark\" aria-hidden=\"true\"></i>"
  url = "/categories"
[[menu.main]]
  weight = 3
  identifier = "tags"
  name = "Tags"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-tags\" aria-hidden=\"true\"></i>"
  url = "/tags"
[[menu.main]]
  weight = 4
  identifier = "archives"
  name = "Archives"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-archive\" aria-hidden=\"true\"></i>"
  url = "/archives"
[[menu.main]]
  weight = 5
  identifier = "about"
  name = "About"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-question\" aria-hidden=\"true\"></i>"
  url = "/#about"

[[menu.links]]
  weight = 1
  identifier = "instagram"
  name = "Instagram"
  pre = "<i class=\"sidebar-button-icon fab fa-lg fa-instagram\" aria-hidden=\"true\"></i>"
  url = "https://www.instagram.com/wege_i_nie/"

[[menu.misc]]
  
# -------------
# Customization
# -------------
[params]

syntaxHighlighter = "highlight.js"

dateFormat = "2006-01-02"

keywords = ["wege i nie", "wegeinie", "wege", "kuchnia", "blw", "weganka", "przepisy", "wegańskie", "przepisy wegańskie"]

clearReading = true

hierarchicalCategories = true

sidebarBehavior = 2

  # Customize link of author avatar in sidebar
  #  [params.sidebar.profile]
  #    url = "/#about"

coverImage = "img/tlo6.jpg"


  imageGallery = true
  thumbnailImage = true
  thumbnailImagePosition = "left"
  autoThumbnailImage = false

favicon = "/favicon.ico"

  # ------------------
  # External resources
  # ------------------
  [[params.customJS]]
    src = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.1.0/languages/apache.min.js"
    integrity = "sha512-gE8KAQyFIzV1C9+GZ8TKJHZS2s+n7EjNtC+IMRn1l5+WYJTHOODUM6JSjZhFhqXmc7bG8Av6XXpckA4tYhflnw=="
    crossorigin = "anonymous"
    async = true
    defer = true

  [[params.customJS]]
    src = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.1.0/languages/go.min.js"
    integrity = "sha512-EWROca+bote+7Oaaar1F6y74iZj1r1F9rm/ly7o+/FwJopbBaWtsFDmaKoZDd3QiGU2pGacBirHJNivmGLYrow=="
    crossorigin = "anonymous"
    async = true
    defer = true

  [[params.customJS]]
    src = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.1.0/languages/http.min.js"
    integrity = "sha512-GDVzAn0wpx1yVtQsRWmFc6PhJiLBPdUic+h4GWgljBh904O3JU10fk9EKNpVyIoPqkFn54rgL2QBG4BmUTMpiQ=="
    crossorigin = "anonymous"
    async = true
    defer = true

  [[params.customJS]]
    src = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.1.0/languages/less.min.js"
    integrity = "sha512-UgZlma8NzkrDb/NWgmLIcTrH7i/CSnLLDRFqCSNF5NGPpjKmzyM25qcoXGOup8+cDakKyaiTDd7N4dyH4YT+IA=="
    crossorigin = "anonymous"
    async = true
    defer = true

  [[params.customJS]]
    src = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.1.0/languages/nginx.min.js"
    integrity = "sha512-lot9koe73sfXIrUvIPM/UEhuMciN56RPyBdOyZgfO53P2lkWyyXN7J+njcxIIBRV+nVDQeiWtiXg+bLAJZDTfg=="
    crossorigin = "anonymous"
    async = true
    defer = true

  [[params.customJS]]
    src = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.1.0/languages/puppet.min.js"
    integrity = "sha512-Zd3e7XxHP00TD0Imr0PIfeM0fl0v95kMWuhyAS3Wn1UTSXTkz0OhtRgBAr4JlmADRgiXr4x7lpeUdqaGN8xIog=="
    crossorigin = "anonymous"
    async = true
    defer = true

  [[params.customJS]]
    src = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.1.0/languages/scss.min.js"
    integrity = "sha512-qtqDO052iXMSP+5d/aE/jMtL9vIIGvONgTJziC2K/ZIB1yEGa55WVxGE9/08rSQ62EoDifS9SWVGZ7ihSLhzMA=="
    crossorigin = "anonymous"
    async = true
    defer = true

  [[params.customJS]]
    src = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.1.0/languages/stylus.min.js"
    integrity = "sha512-1NmkjnEDnwwwcu28KoQF8vs3oaPFokQHbmbtwGhFfeDsQZtVFI8zW2aE9O8yMYdpdyKV/5blE4pSWw4Z/Sv97w=="
    crossorigin = "anonymous"
    async = true
    defer = true

  [[params.customJS]]
    src = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.1.0/languages/swift.min.js"
    integrity = "sha512-B2wSfruPjr8EJL6IIzQr1eAuDwrsfIfccNf/LCEdxELCgC/S/ZMt/Uvk80aD79m7IqOqW+Sw8nbkvha20yZpzg=="
    crossorigin = "anonymous"
    async = true
    defer = true

  [[params.customJS]]
    src = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.1.0/languages/yaml.min.js"
    integrity = "sha512-28oDiQZGKUVN6wQ7PSLPNipOcmkCALXKwOi7bnkyFf8QiMZQxG9EQoy/iiNx6Zxj2cG2SbVa4dXKigQhu7GiFw=="
    crossorigin = "anonymous"
    async = true
    defer = true

  # ---------------
  # Sharing options
  # ---------------
  # Comment and uncomment to enable or disable sharing options
  # If you wanna add a sharing option, read user documentation :
  # Tranquilpeak configuration > Theme configuration > sharing-options
  [[params.sharingOptions]]
    name = "Facebook"
    icon = "fab fa-facebook-square"
    url = "https://www.facebook.com/sharer/sharer.php?u=%s"

  [[params.sharingOptions]]
    name = "Twitter"
    icon = "fab fa-twitter"
    url = "https://twitter.com/intent/tweet?text=%s"

  [[params.sharingOptions]]
    name = "Whatsapp"
    icon = "fab fa-whatsapp"
    url = "https://wa.me/?text=%s"

  # -------------------
  # Integrated services
  # -------------------
  # Google Analytics
  #  >> See googleAnalytics
  #    googleAnalytics =
  # Your Facebook user ids used to connect your blog with your facebook user accounts (Facebook Insights). Separate ids with comma. e.g : 9830047,1003342
  #  fbAdminIds =
  # Your Facebook app id used to connect your blog with your facebook app account (Facebook Insights). E.g : 9841307
  #  fbAppId =

  # --------------
  # Comment system
  # --------------
  [params.comment]
    [params.comment.disqus]
      enable = true
      shortname = "wege-i-nie"
    [params.comment.gitalk]
      enable = false
      # clientId =
      # clientSecret =
      # owner =
      # repo =
      # See all options: https://github.com/gitalk/gitalk#options
      [params.comment.gitalk.options]
        language = "en"
        perPage = 10
        distractionFreeMode = false
        enableHotKey = true
        pagerDirection = "first"

  # --------------------
  # Header configuration
  # --------------------
  # The link at the right of the header is customizable
  # You can add a link (as an icon) at the right of the header instead of the author's gravatar image or author's picture.
  # By default, author's gravatar or author's picture is displayed.
  [params.header.rightLink]
  class = ""
  icon = ""
  url = "/#about"
  
  # --------------------
  # Footer configuration
  # --------------------
  # Customize copyright value "© 2017 <CUSTOMIZATION>. All Rights Reserved"
[params.footer]
copyright = "<a href=\"https://github.com/kakawait\">Hugo tranquilpeak theme</a>"
